image: gitpod/workspace-full

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - before: git config --global user.email "963151+DoPaNik@users.noreply.github.com"
  - init: npm install
  - init: yarn --network-timeout 100000 && yarn build
    command: yarn dev --host 0.0.0.0

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components@0.0.29:7hF8G3VtB+HNearI5Zw+NA==