// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintPluginAstro from 'eslint-plugin-astro';
import eslintConfigPrettier from 'eslint-config-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      '.astro/**',
      'node_modules/**',
      // Generated by `npm run build:critical-scripts` (esbuild output) — lint the
      // TypeScript source at src/scripts/theme-bootstrap.ts instead.
      'public/scripts/theme-bootstrap.js',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  eslintConfigPrettier,
  {
    files: ['scripts/**/*.mjs', 'eslint.config.js', 'astro.config.mjs', '.lighthouserc.cjs'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    files: ['src/**/*.astro', 'src/scripts/**/*.ts'],
    languageOptions: {
      globals: globals.browser,
    },
  },
);
